/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.game.Card;
import org.game.Ranks;
import org.game.Suits;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Card aceSpade = new Card(Suits.SPADE, Ranks.ACE);
        aceSpade.printCard();
    }
}
